name: Remove triage label
on:
  issues:
    types:
      - labeled

permissions:
  issues: write

jobs:
  remove-triage-label-from-issues:
    if:
      github.event.label.name != 'triage' && github.event.label.name !=
      'more-info-needed'
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - run: gh issue edit "$NUMBER" --remove-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: triage
